# Use postgres/example user/password credentials
version: '3.9'

services:
  service:
    build: .
    container_name: service
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
    depends_on:
      - db
      - jaeger
  jaeger:
    image: jaegertracing/all-in-one:1.35
    container_name: jaeger-all-in-one
    ports:
      - "16686:16686"
      - "4317:4317" #grpc
      - "4318:4318" #http
    environment:
      - COLLECTOR_OTLP_ENABLED=true
  db:
    image: postgres
    container_name: db
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=prisma

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
